  # api:
  #   image: ${DOCKER_REGISTRY-}api
  #   build:
  #     context: .
  #     dockerfile: Bootstrapper/Api/Dockerfile

version: '3.4'

services:
 eshopdb:
  image: postgres

volumes:
  postgres_eshopdb:
